### PR TITLE
(attempting to) Fix SpikeHD/Dorion#107

### PR DESCRIPTION
**Pull request by Banaanae**
There are two issues in SpikeHD/Dorion#107

* [x] Open QuickCss button
* [X] Open in github and donate buttons

### CODE REVIEW

**Comment by Banaanae** [comment]
messed up issue linking, didnt mean to link to 107 in the vencord repo

**Comment by Banaanae** [comment]
No luck fixing quickcss yet, can do something like this if needed
image
maybe redirect to themes folder?

**Comment by Banaanae** [comment]
Can't find issue, will put ready for review
If you want the suggestions above implemented leave a comment

**Comment by Banaanae** [comment]
Saw https://github.com/SpikeHD/Vencordorion/commit/974d547603e44c1d40cd0c51971559b772b7e87f, removed button.

**Comment by SpikeHD** [comment]
Rebuild Dorion, I already fixed a bunch of link behaviour here https://github.com/SpikeHD/Dorion/commit/f4edc0c638f146bbd1e2242fcab6ca02a571335d (not quickcss nor stream popouts, those are more complex issues)

**Comment by SpikeHD** [comment]
That and I would prefer for those buttons to be hidden via CSS here: https://github.com/SpikeHD/Dorion/blob/main/src/extra.css

Prevents merges conflicts when I update Vencordorion with upstream Vencord

**Pull request closed without merging**
